# Setup
title:               Ahmed Ratnani 
tagline:             'Applied Mathematician & Computer Scientist.'
description:         'Applied Mathematician & Computer Scientist.'
url:                 https://ratnania.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
github_username:     ratnania 

markdown: kramdown
kramdown:
  math_engine: mathjax

# About/contact
author:
  name:              Ahmed Ratnani 
  email:             ratnania@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
